export const actionTypes = {
  UPDATE_LOGIN_DETAILS: "UPDATE_LOGIN_DETAILS",
  UPDATE_SIGNUP_DETAILS: "UPDATE_SIGNUP_DETAILS",
  SIGN_IN_USER_REQUEST: "SIGN_IN_USER_REQUEST",
  SIGN_IN_USER_SUCCESS: "SIGN_IN_USER_SUCCESS",
  SIGN_IN_USER_FAILURE: "SIGN_IN_USER_FAILURE",
};
