export const actionTypes = {
    UPDATE_LOGIN_DETAILS: "UPDATE_LOGIN_DETAILS",
    UPDATE_SIGNUP_DETAILS: "UPDATE_SIGNUP_DETAILS",
    UPDATE_LOGIN_FORM_ERROR: "UPDATE_LOGIN_FORM_ERROR",
    UPDATE_SIGNUP_FORM_ERROR: "UPDATE_SIGNUP_FORM_ERROR"
}
